-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 10:55:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pais` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `idPais` INT NOT NULL,
  `nombrePais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPais`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `cedula` INT NOT NULL,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `primerApellidoPesona` VARCHAR(45) NOT NULL,
  `segundoApellidoPersona` VARCHAR(45) NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`cedula`),
  INDEX `fk_Persona_Pais1_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Persona_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CorreoXPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CorreoXPersona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`CorreoXPersona` (
  `idCorreo` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `Persona_cedula` INT NOT NULL,
  PRIMARY KEY (`idCorreo`),
  INDEX `fk_correosXpersona_Persona1_idx` (`Persona_cedula` ASC),
  CONSTRAINT `fk_correosXpersona_Persona1`
    FOREIGN KEY (`Persona_cedula`)
    REFERENCES `mydb`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Provincia` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombreProvincia` VARCHAR(45) NOT NULL,
  `Pais_idPais` INT NOT NULL,
  PRIMARY KEY (`idProvincia`),
  INDEX `fk_Provincia_Pais1_idx` (`Pais_idPais` ASC),
  CONSTRAINT `fk_Provincia_Pais1`
    FOREIGN KEY (`Pais_idPais`)
    REFERENCES `mydb`.`Pais` (`idPais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Canton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Canton` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Canton` (
  `idCanton` INT NOT NULL,
  `nombreCanton` VARCHAR(45) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCanton`),
  INDEX `fk_Canton_Provincia1_idx` (`Provincia_idProvincia` ASC),
  CONSTRAINT `fk_Canton_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia`)
    REFERENCES `mydb`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Distrito` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Distrito` (
  `idDistrito` INT NOT NULL,
  `nombreDistrito` VARCHAR(45) NOT NULL,
  `Canton_idCanton` INT NOT NULL,
  PRIMARY KEY (`idDistrito`),
  INDEX `fk_Distrito_Canton1_idx` (`Canton_idCanton` ASC),
  CONSTRAINT `fk_Distrito_Canton1`
    FOREIGN KEY (`Canton_idCanton`)
    REFERENCES `mydb`.`Canton` (`idCanton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB NULL,
  `precio` DECIMAL NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Localizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Localizacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Localizacion` (
  `codigo` INT NOT NULL,
  `coordenadaX` FLOAT NOT NULL,
  `coordenadaY` FLOAT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`CentroAcopio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CentroAcopio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`CentroAcopio` (
  `idcentroAcopio` INT NOT NULL,
  `nombreCentroAcopio` VARCHAR(45) NOT NULL,
  `encargado` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `Localizacion_codigo` INT NOT NULL,
  `Distrito_idDistrito` INT NOT NULL,
  PRIMARY KEY (`idcentroAcopio`),
  INDEX `fk_centroAcopio_Localizacion1_idx` (`Localizacion_codigo` ASC),
  INDEX `fk_centroAcopio_Distrito1_idx` (`Distrito_idDistrito` ASC),
  CONSTRAINT `fk_centroAcopio_Localizacion1`
    FOREIGN KEY (`Localizacion_codigo`)
    REFERENCES `mydb`.`Localizacion` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centroAcopio_Distrito1`
    FOREIGN KEY (`Distrito_idDistrito`)
    REFERENCES `mydb`.`Distrito` (`idDistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TelefonoXPersona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TelefonoXPersona` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TelefonoXPersona` (
  `idtelefonosXpesona` INT UNSIGNED NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `Persona_cedula` INT NOT NULL,
  PRIMARY KEY (`idtelefonosXpesona`),
  INDEX `fk_telefonosXpesona_Persona1_idx` (`Persona_cedula` ASC),
  CONSTRAINT `fk_telefonosXpesona_Persona1`
    FOREIGN KEY (`Persona_cedula`)
    REFERENCES `mydb`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TipoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TipoUsuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TipoUsuario` (
  `idtipoUsuario` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `puntosActuales` INT NULL,
  `puntosGastados` INT NULL,
  `puntosTotales` INT NULL,
  `tipoUsuario_idtipoUsuario` INT NOT NULL,
  `Persona_cedula` INT NOT NULL,
  PRIMARY KEY (`nombreUsuario`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC),
  INDEX `fk_Usuario_tipoUsuario1_idx` (`tipoUsuario_idtipoUsuario` ASC),
  INDEX `fk_Usuario_Persona1_idx` (`Persona_cedula` ASC),
  CONSTRAINT `fk_Usuario_tipoUsuario1`
    FOREIGN KEY (`tipoUsuario_idtipoUsuario`)
    REFERENCES `mydb`.`TipoUsuario` (`idtipoUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_cedula`)
    REFERENCES `mydb`.`Persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`EquivalenciaMaterial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EquivalenciaMaterial` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`EquivalenciaMaterial` (
  `idTipo` INT NOT NULL,
  `peso` VARCHAR(45) NOT NULL,
  `puntos` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Comercio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comercio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Comercio` (
  `idComercio` INT NOT NULL AUTO_INCREMENT,
  `nombreComercio` VARCHAR(45) NOT NULL,
  `nombreEncargado` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idComercio`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ProductoXUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoXUsuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoXUsuario` (
  `Producto_idProducto` INT NOT NULL,
  `Usuario_nombreUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Usuario_nombreUsuario`),
  INDEX `fk_Producto_has_Usuario_Usuario1_idx` (`Usuario_nombreUsuario` ASC),
  INDEX `fk_Producto_has_Usuario_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Producto_has_Usuario_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_nombreUsuario`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ProductoXComercio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoXComercio` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ProductoXComercio` (
  `Producto_idProducto` INT NOT NULL,
  `Comercio_idComercio` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Comercio_idComercio`),
  INDEX `fk_Producto_has_Comercio_Comercio1_idx` (`Comercio_idComercio` ASC),
  INDEX `fk_Producto_has_Comercio_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Producto_has_Comercio_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_Comercio_Comercio1`
    FOREIGN KEY (`Comercio_idComercio`)
    REFERENCES `mydb`.`Comercio` (`idComercio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Puntos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Puntos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Puntos` (
  `idPuntos` INT NOT NULL,
  `idTipoPuntos` INT NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `fechaHoraTransaccionPuntos` DATETIME NOT NULL,
  `Usuario_nombreUsuario` VARCHAR(45) NOT NULL,
  `centroAcopio_idcentroAcopio` INT NOT NULL,
  PRIMARY KEY (`idPuntos`),
  INDEX `fk_Puntos_Usuario1_idx` (`Usuario_nombreUsuario` ASC),
  INDEX `fk_Puntos_centroAcopio1_idx` (`centroAcopio_idcentroAcopio` ASC),
  CONSTRAINT `fk_Puntos_Usuario1`
    FOREIGN KEY (`Usuario_nombreUsuario`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Puntos_centroAcopio1`
    FOREIGN KEY (`centroAcopio_idcentroAcopio`)
    REFERENCES `mydb`.`CentroAcopio` (`idcentroAcopio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
