-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 10:22:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BanderaAzul
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BanderaAzul
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BanderaAzul` DEFAULT CHARACTER SET utf8 ;
USE `BanderaAzul` ;
USE `BanderaAzul`;

DELIMITER $$

USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Pais_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Pais_BEFORE_INSERT` BEFORE INSERT ON `Pais` FOR EACH ROW
BEGIN
	INSERT INTO `Pais`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Pais_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Pais_BEFORE_UPDATE` BEFORE UPDATE ON `Pais` FOR EACH ROW
BEGIN
	INSERT INTO `Pais`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Provincia_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Provincia_BEFORE_INSERT` BEFORE INSERT ON `Provincia` FOR EACH ROW
BEGIN
	INSERT INTO `Provincia`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Provincia_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Provincia_BEFORE_UPDATE` BEFORE UPDATE ON `Provincia` FOR EACH ROW
BEGIN
	INSERT INTO `Provincia`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Canton_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Canton_BEFORE_INSERT` BEFORE INSERT ON `Canton` FOR EACH ROW
BEGIN
	INSERT INTO `Canton`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Canton_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Canton_BEFORE_UPDATE` BEFORE UPDATE ON `Canton` FOR EACH ROW
BEGIN
	INSERT INTO `Canton`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Distrito_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Distrito_BEFORE_INSERT` BEFORE INSERT ON `Distrito` FOR EACH ROW
BEGIN
	INSERT INTO `Distrito`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Distrito_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Distrito_BEFORE_UPDATE` BEFORE UPDATE ON `Distrito` FOR EACH ROW
BEGIN
	INSERT INTO `Distrito`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Persona_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Persona_BEFORE_INSERT` BEFORE INSERT ON `Persona` FOR EACH ROW
BEGIN
	INSERT INTO `Persona`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Persona_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Persona_BEFORE_UPDATE` BEFORE UPDATE ON `Persona` FOR EACH ROW
BEGIN
	INSERT INTO `Persona`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`CorreoXPersona_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`CorreoXPersona_BEFORE_INSERT` BEFORE INSERT ON `CorreoXPersona` FOR EACH ROW
BEGIN
	INSERT INTO `CorreoXPersona`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`CorreoXPersona_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`CorreoXPersona_BEFORE_UPDATE` BEFORE UPDATE ON `CorreoXPersona` FOR EACH ROW
BEGIN
	INSERT INTO `CorreoXPersona`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TipoUsuario_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TipoUsuario_BEFORE_INSERT` BEFORE INSERT ON `TipoUsuario` FOR EACH ROW
BEGIN
	INSERT INTO ``(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TipoUsuario_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TipoUsuario_BEFORE_UPDATE` BEFORE UPDATE ON `TipoUsuario` FOR EACH ROW
BEGIN
	INSERT INTO `TipoUsuario`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Usuario_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Usuario_BEFORE_INSERT` BEFORE INSERT ON `Usuario` FOR EACH ROW
BEGIN
	INSERT INTO `Usuario`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Usuario_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Usuario_BEFORE_UPDATE` BEFORE UPDATE ON `Usuario` FOR EACH ROW
BEGIN
	INSERT INTO `Usuario`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TipoComercio_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TipoComercio_BEFORE_INSERT` BEFORE INSERT ON `TipoComercio` FOR EACH ROW
BEGIN
	INSERT INTO `TipoComercio`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TipoComercio_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TipoComercio_BEFORE_UPDATE` BEFORE UPDATE ON `TipoComercio` FOR EACH ROW
BEGIN
	INSERT INTO `TipoComercio`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Comercio_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Comercio_BEFORE_INSERT` BEFORE INSERT ON `Comercio` FOR EACH ROW
BEGIN
		INSERT INTO `Comercio`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Comercio_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Comercio_BEFORE_UPDATE` BEFORE UPDATE ON `Comercio` FOR EACH ROW
BEGIN
	INSERT INTO `Comercio`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Producto_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Producto_BEFORE_INSERT` BEFORE INSERT ON `Producto` FOR EACH ROW
BEGIN
	INSERT INTO `Producto`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());

END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Producto_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Producto_BEFORE_UPDATE` BEFORE UPDATE ON `Producto` FOR EACH ROW
BEGIN
	INSERT INTO `Producto`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Localizacion_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Localizacion_BEFORE_INSERT` BEFORE INSERT ON `Localizacion` FOR EACH ROW
BEGIN
	INSERT INTO `Localizacion`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Localizacion_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Localizacion_BEFORE_UPDATE` BEFORE UPDATE ON `Localizacion` FOR EACH ROW
BEGIN
	INSERT INTO `Localizacion`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`CentroAcopio_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`CentroAcopio_BEFORE_INSERT` BEFORE INSERT ON `CentroAcopio` FOR EACH ROW
BEGIN
	INSERT INTO `CentroAcopio`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`CentroAcopio_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`CentroAcopio_BEFORE_UPDATE` BEFORE UPDATE ON `CentroAcopio` FOR EACH ROW
BEGIN
	INSERT INTO `CentroAcopio`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TelefonoXPersona_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TelefonoXPersona_BEFORE_INSERT` BEFORE INSERT ON `TelefonoXPersona` FOR EACH ROW
BEGIN
	INSERT INTO `TelefonoXPersona`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`TelefonoXPersona_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`TelefonoXPersona_BEFORE_UPDATE` BEFORE UPDATE ON `TelefonoXPersona` FOR EACH ROW
BEGIN
	INSERT INTO `TelefonoXPersona`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`EquivalenciaMaterial_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`EquivalenciaMaterial_BEFORE_INSERT` BEFORE INSERT ON `EquivalenciaMaterial` FOR EACH ROW
BEGIN
	INSERT INTO `EquivalenciaMaterial`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`EquivalenciaMaterial_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`EquivalenciaMaterial_BEFORE_UPDATE` BEFORE UPDATE ON `EquivalenciaMaterial` FOR EACH ROW
BEGIN
	INSERT INTO `EquivalenciaMaterial`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`ProductoXUsuario_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`ProductoXUsuario_BEFORE_INSERT` BEFORE INSERT ON `ProductoXUsuario` FOR EACH ROW
BEGIN
	INSERT INTO `ProductoXUsuario`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`ProductoXUsuario_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`ProductoXUsuario_BEFORE_UPDATE` BEFORE UPDATE ON `ProductoXUsuario` FOR EACH ROW
BEGIN
		INSERT INTO `ProductoXUsuario`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Puntos_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Puntos_BEFORE_INSERT` BEFORE INSERT ON `Puntos` FOR EACH ROW
BEGIN
	INSERT INTO `Puntos`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`Puntos_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`Puntos_BEFORE_UPDATE` BEFORE UPDATE ON `Puntos` FOR EACH ROW
BEGIN
	INSERT INTO `Puntos`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`cambioClave_BEFORE_INSERT` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`cambioClave_BEFORE_INSERT` BEFORE INSERT ON `cambioClave` FOR EACH ROW
BEGIN
	INSERT INTO `cambioClave`(`fecCreacion`, `usuarioCreacion`) values (NOW(), CURRENT_USER());
END$$


USE `BanderaAzul`$$
DROP TRIGGER IF EXISTS `BanderaAzul`.`cambioClave_BEFORE_UPDATE` $$
USE `BanderaAzul`$$
CREATE DEFINER = CURRENT_USER TRIGGER `BanderaAzul`.`cambioClave_BEFORE_UPDATE` BEFORE UPDATE ON `cambioClave` FOR EACH ROW
BEGIN
	INSERT INTO `cambioClave`(`fecultimaModificacion`, `usuarioUltimaModificacion`) values (NOW(), CURRENT_USER());
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
